apiVersion: v1
kind: Pod
metadata:
  labels:
    application: mysql
  name: mysql
spec:
  containers:
  - env:
    - name: MYSQL_ROOT_PASSWORD
      value: "123456"
    image: registry.ocp311.ocp.local:5000/testimages/mysql:5.7
    imagePullPolicy: IfNotPresent
    name: mysql
    ports:
    - containerPort: 3306
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      initialDelaySeconds: 5
      periodSeconds: 5
      successThreshold: 1
      tcpSocket:
        port: 3306
      timeoutSeconds: 1
    resources: {}
    volumeMounts:
    - mountPath: /var/lib/mysql
      name: mysql-volume
  nodeSelector:
    node-role.kubernetes.io/compute: "true"
  restartPolicy: Always
  #securityContext:
  #  seLinuxOptions:
  #3    level: s0:c25,c20
  volumes:
  - name: mysql-volume
    persistentVolumeClaim:
      claimName: pvc01
