kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv01
spec:
  capacity:
    storage: 1Gi
  nfs:
    server: 10.10.15.20
    path: /mnt/nfs_data/volumes/pv01
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
