apiVersion: v1
kind: Template
metadata:
  name: redis-template
  annotations:
    description: "template demo"
    iconClass: "f111"
    tags: "database,nosql"
objects: 
- apiVersion: v1
  kind: Pod
  metadata:
    name: redis-master
  spec:
    containers:
    - env:
      - name: REDIS_PASSWORD
        value: ${REDIS_PASSWORD}
      image: redis:latest
      name: master
      ports:
      - containerPort: 6379
        protocol: TCP
parameters:
- description: Password used for Redis authentication
  from: '[A-Z0-9]{8}'
  generate: expression
  name: REDIS_PASSWORD
labels: 
  redis: master
